from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class ProjectConfig:
    name: str
    sensors: list[str]
    anomalies: list[str]
    environments: list[str]


def _yaml_lines(data: object, indent: int = 0) -> list[str]:
    prefix = "  " * indent
    if isinstance(data, dict):
        lines: list[str] = []
        for key, value in data.items():
            if isinstance(value, (dict, list)):
                lines.append(f"{prefix}{key}:")
                lines.extend(_yaml_lines(value, indent + 1))
            else:
                lines.append(f"{prefix}{key}: {value}")
        return lines
    if isinstance(data, list):
        lines = []
        for item in data:
            if isinstance(item, (dict, list)):
                lines.append(f"{prefix}-")
                lines.extend(_yaml_lines(item, indent + 1))
            else:
                lines.append(f"{prefix}- {item}")
        return lines
    return [f"{prefix}{data}"]


def _write_yaml(path: Path, data: dict[str, object]) -> None:
    lines = _yaml_lines(data)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def create_project(config: ProjectConfig, output_dir: Path) -> Path:
    project_dir = output_dir / config.name
    project_dir.mkdir(parents=True, exist_ok=True)

    config_dir = project_dir / "config"
    sensors_dir = project_dir / "sensors"
    simulated_dir = sensors_dir / "simulated"
    models_dir = project_dir / "models"
    pipelines_dir = project_dir / "pipelines"
    scripts_dir = project_dir / "scripts"
    data_dir = project_dir / "data"
    env_dir = project_dir / "environments"

    for directory in [
        config_dir,
        simulated_dir,
        models_dir,
        pipelines_dir,
        scripts_dir,
        data_dir,
        env_dir,
    ]:
        directory.mkdir(parents=True, exist_ok=True)

    _write_yaml(
        config_dir / "wristband_config.yaml",
        {
            "project": {
                "name": config.name,
                "created_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
            },
            "sensors": config.sensors,
            "anomalies": config.anomalies,
            "environments": config.environments,
        },
    )

    (project_dir / "README.md").write_text(
        """# Wristband Sensor Fusion Project\n\n"
        "This project was generated by the Altrus CLI.\n"
        "Update `config/wristband_config.yaml` to adjust sensors, anomalies, or environments.\n",
        encoding="utf-8",
    )

    (models_dir / "user_model.py").write_text(
        """\"\"\"Replace this stub with your trained model.\"\"\"\n\n"
        "class UserModel:\n"
        "    \"\"\"Simple stub for a wristband anomaly model.\"\"\"\n\n"
        "    def predict(self, features: list[float]) -> dict:\n"
        "        \"\"\"Return a dummy prediction for now.\"\"\"\n"
        "        return {\"anomaly\": False, \"score\": 0.0}\n\n"
        "\n"
        "def load_model() -> UserModel:\n"
        "    return UserModel()\n",
        encoding="utf-8",
    )

    (pipelines_dir / "inference.py").write_text(
        """from __future__ import annotations\n\n"
        "from models.user_model import load_model\n\n"
        "\n"
        "def run_inference(features: list[float]) -> dict:\n"
        "    model = load_model()\n"
        "    return model.predict(features)\n",
        encoding="utf-8",
    )

    (scripts_dir / "run_inference.py").write_text(
        """from pipelines.inference import run_inference\n\n"
        "\n"
        "def main() -> None:\n"
        "    sample_features = [0.0, 0.0, 0.0]\n"
        "    result = run_inference(sample_features)\n"
        "    print(f\"Inference result: {result}\")\n\n"
        "\n"
        "if __name__ == \"__main__\":\n"
        "    main()\n",
        encoding="utf-8",
    )

    (simulated_dir / "simulator.py").write_text(
        """from __future__ import annotations\n\n"
        "import random\n\n"
        "\n"
        "def generate_sample() -> dict:\n"
        "    \"\"\"Generate a simulated sensor reading.\"\"\"\n"
        "    return {\n"
        "        \"accel_x\": random.uniform(-1.0, 1.0),\n"
        "        \"accel_y\": random.uniform(-1.0, 1.0),\n"
        "        \"accel_z\": random.uniform(-1.0, 1.0),\n"
        "    }\n",
        encoding="utf-8",
    )

    (simulated_dir / "README.md").write_text(
        """# Simulated Sensors\n\n"
        "Use this folder to extend simulated sensor generation for testing.\n",
        encoding="utf-8",
    )

    for environment in config.environments:
        (env_dir / f"{environment}.md").write_text(
            f"# {environment.replace('_', ' ').title()} Setup\n\n"
            "Document environment-specific setup steps here.\n",
            encoding="utf-8",
        )

    return project_dir
